# Generated by Django 3.0.2 on 2020-01-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedBy', models.CharField(max_length=100)),
                ('song', models.FileField(upload_to='uploaded/')),
            ],
        ),
    ]
